# List 
 The most basic data structure in Python is the sequence.<br>
Each element of a sequence is assigned a number - its position or index. The indexing starts from 0.

In [ ]:
list1 = ['physics', 'chemistry', 1997, 2000]
list2 = [1, 2, 3, 4, 5 ]
list3 = ["a", "b", "c", "d"]

In [ ]:
# Accessing Values in Lists
print("list1[0]: ", list1[0])
print("list2[1:5]: ", list2[1:5])
print()
print("Accessing the last element of list1: ",list1[-1])

In [ ]:
# Updating the list
list1[3]=3000
print("Updated list",list1)
# Append New element to list
list1.append(1)
print("List after appending new item",list1)

In [ ]:
# Deleting Elements from List
del list1[0]
print(list1)

<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;">Function with Description</th>
</tr>
<tr>
<td>cmp(list1, list2)
<p>Compares elements of both lists.</p></td>
</tr>
<tr>
<td>len(list)
<p>Gives the total length of the list.</p></td>
</tr>
<tr>
<td>max(list)
<p>Returns item from the list with max value.</p></td>
</tr>
<tr>
<td>min(list)
<p>Returns item from the list with min value.</p></td>
</tr>
<tr>
<td>list(seq)
<p>Converts a tuple into list.</p></td>
</tr>
</tbody></table>

<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;width:100%">Methods with Description</th>
</tr>
<tr>
<td>list.append(obj)
<p>Appends object obj to list</p></td>
</tr>
<tr>
<td>list.count(obj)
<p>Returns count of how many times obj occurs in list</p></td>
</tr>
<tr>
<td>list.extend(seq)
<p>Appends the contents of seq to list</p></td>
</tr>
<tr>
<td>list.index(obj)
<p>Returns the lowest index in list that obj appears</p></td>
</tr>
<tr>
<td>list.insert(index, obj)
<p>Inserts object obj into list at offset index</p></td>
</tr>
<tr>
<td>list.pop(obj=list[-1])
<p>Removes and returns last object or obj from list</p></td>
</tr>
<tr>
<td>list.remove(obj)
<p>Removes object obj from list</p></td>
</tr>
<tr>
<td>list.reverse()
<p>Reverses objects of list in place</p></td>
</tr>
<tr>
<td>list.sort([func])
<p>Sorts objects of list, use compare func if given</p></td>
</tr>
</tbody></table>

# Questions 

1. Program to find the sum of elements and sum of square of n numbers in a list

In [ ]:
# Answer 1
listt=input("Enter list elements: ").split()
sum=0
sq=0
for i in range(0,len(listt)):
  sum+=int(listt[i])
  sq+=pow(int(listt[i]),2)
print(f"Sum= {sum}")
print(f"sum of squares= {sq}")

Enter list elements: 1 2 3 4
Sum= 10
sum of squares= 30


2. Python Program to find largest element in an array and also second largest number

In [ ]:
# Answer 2
listt=input("Enter list elements: ").split()
listt.sort()
print(f"Largest : {listt[-1]}")
print(f"Second largest : {listt[-2]}")

Enter list elements: 5 3 4 7 6
Largest : 7
Second largest : 6


3. Remove multiple elements from a list in Python

In [ ]:
# Answer 3
from collections import Counter
listt=input("Enter list elements: ").split()
rem=input("Enter elements to remove: ").split()
listt = list((Counter(listt) - Counter(rem)).elements())
listt

Enter list elements: 1 2 3 4 5
Enter elements to remove: 2 5


['1', '3', '4']

4.  Find the difference of sum of odd number and even number.

In [ ]:
#Answer
listt=input("Enter list elements: ").split()
odd=[]
even=[]
for i in range(0,len(listt)):
  if int(listt[i])%2==0:
    even.append(listt[i])
  else:
    odd.append(listt[i])
for i in range(0,len(even)):
  sume+=int(even[i])
for i in range(0,len(odd)):
  sumo+=int(odd[i])
print(f"difference of sum of odd number and even number : {sumo-sume}")


Enter list elements: 1 2 3 4 5 6 7
difference of sum of odd number and even number : 5


5. Program to reverse a List

In [ ]:
#Answer
listt=input("Enter list elements: ").split()
listt.reverse()
listt

Enter list elements: 1 2 3 4 5


['5', '4', '3', '2', '1']

6. Write a program to find the frequency of each element in a user input list.

        Point To Remember:    Use a dictionary to keep track of count of each element in the list
            Dictionary should be like <br>
            {  array_element1: count1, array_element2: count2} 

In [ ]:
#Answer
from collections import Counter
listt=input("Enter list elements: ").split()
x=dict(Counter(listt))
x

Enter list elements: 1 2 2 3 3 3 4 4 5 5 6


{'1': 1, '2': 2, '3': 3, '4': 2, '5': 2, '6': 1}

7. Write a program to find the most occurring element in a user input list. If there are no repeated
elements at all , then a message, “No duplication” should be displayed.


In [ ]:
#Answer
from statistics import mode
listt=input("Enter list elements: ").split()
try:
  print(f"most occurring element : {mode(listt)}")
except:
  print("No duplication")


  

Enter list elements: 1 2 3 4 5
No duplication


8. Write a program to display all the Armstrong numbers present in a list. If no such numbers are
present, an appropriate message should be displayed. (Armstrong number is a number that is equal to the sum of cubes of its digits)


In [ ]:
#Answer
listt=input("Enter list elements: ").split()
arm=[]

for i in range(0,len(listt)):
  sum=0
  num=int(listt[i])
  temp = num
  while temp > 0:
    digit = temp % 10
    sum += digit ** 3
    temp //= 10
  if int(listt[i])==sum:
    arm.append(listt[i])

if len(arm)==0:
  print("No armstrong numbers are present")
else:
  print(f"armstrong numbers in the list {arm}")
    
  


Enter list elements: 1 2 3 4 0 153
armstrong numbers in the list ['1', '0', '153']


9. Write a program to accept two lists and print “Overlapped” if they have at least one element in
common, otherwise display “separated”.

        Logic: Set intersection will be helpful to check whether the 2 list have any elements in common

In [ ]:
#Answer
x=input("Enter list1 elements: ").split()
y=input("Enter list2 elements: ").split()
r=set(x) & set(y)
if len(r)==0:
  print("Seperated")
else:
  print("Overlapped")

Enter list1 elements: 1 2 3 4 5
Enter list2 elements: 4 5 6 7 8
Overlapped


10. Write a program to accept a list and rearrange the elements in such a way that all the even
elements appear on the left side of the new list and odd elements in the right side as follows:
If the user input list is [1,20,3,4,5,6]
Then the new list should be [20,4,6,5,3,1]

    Point to remember:
        Create 2 lists one for odd and other for even
        Append both the list

In [ ]:
#Answer
listt=input("Enter list elements: ").split()
odd=[]
even=[]
for i in range(0,len(listt)):
  if int(listt[i])%2==0:
    even.append(listt[i])
  else:
    odd.append(listt[i])
res=even+odd
res

Enter list elements: 1 2 3 4 5 6


['2', '4', '6', '1', '3', '5']

# Tuple
A tuple is a collection of objects which ordered and immutable. <br>
Tuples are sequences. The differences between tuples and lists are, the tuples cannot be changed unlike lists and tuples use parentheses, whereas lists use square brackets.


In [ ]:
tup1 = ('physics', 'chemistry', 1997, 2000);
tup2 = (1, 2, 3, 4, 5 );
tup3 = "a", "b", "c", "d";

# Print the first element of tuple
print(tup1[0])

# Print a range of values 
print("tup2[1:5]: ", tup2[1:5]);

# 

<b>Basic tuple operations</b><br>
<table class="table table-bordered" style="text-align:center;">
<tbody><tr>
<th style="text-align:center;">Python Expression</th>
<th style="text-align:center;">Results</th>
<th style="text-align:center;">Description</th>
</tr>
<tr>
<td>len((1, 2, 3))</td>
<td>3</td>
<td>Length</td>
</tr>
<tr>
<td>(1, 2, 3) + (4, 5, 6)</td>
<td>(1, 2, 3, 4, 5, 6)</td>
<td>Concatenation</td>
</tr>
<tr>
<td>('Hi!',) * 4</td>
<td>('Hi!', 'Hi!', 'Hi!', 'Hi!')</td>
<td>Repetition</td>
</tr>
<tr>
<td>3 in (1, 2, 3)</td>
<td>True</td>
<td>Membership</td>
</tr>
<tr>
<td>for x in (1, 2, 3): print x,</td>
<td>1 2 3</td>
<td>Iteration</td>
</tr>
</tbody></table>

11. Python program to find Maximum and Minimum K elements in Tuple (we need to extract only extreme K elements, i.e maximum and minimum K elements in Tuple)
    
        Input : test_tup = (3, 7, 1, 18, 9), k = 2 
        Output : (3, 1, 9, 18)
        
        Input : test_tup = (3, 7, 1), k=1 
        Output : (1, 3) 

In [ ]:
# Answer
tup=tuple(input("Enter list elements: ").split())
n= int(input("Enter extreme : "))
res = []
tup = list(sorted(tup))
for i, val in enumerate(tup):
    if i < n or i >= len(tup) - n:
        res.append(val)
res = tuple(res)
res


Enter list elements: 7 5 3 1 4 2 6
Enter extreme : 2


('1', '2', '6', '7')

12. Python program to demonstrate the addition of elements in a Tuple.

In [ ]:
# Answer
tup=tuple(input("Enter list elements: ").split())
s=0
for i in range(0,len(tup)):
  s+=int(tup[i])
s

Enter list elements: 1 2 3 4 5


15

 Dictionary

In [ ]:
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
print("dict['Name']: ", dict['Name'])
print("dict['Age']: ", dict['Age'])

13. Program to create a dictionary which store student roll number as key and name as value.<br>
And write a program to search the dictionary using roll number and diplay the name of student.

In [ ]:
#Answer
d={}
x=int(input("enter no of records : "))
for i in range(0,x):
  n=input(f"Enter rollno{i}:")
  na=input(f"Enter name{i}:")
  d[n]=na
res=None
ser=input("Enter roll no to search: ")
d[ser]

enter no of records : 2
Enter rollno0:1
Enter name0:Ashiq
Enter rollno1:2
Enter name1:Ameer
Enter roll no to search: 2


'Ameer'

14. <b>Caesar cipher Encryption and Decription</b> <br>

<table class="wikitable"><tbody><tr style="vertical-align:top"><th scope="row">  Plain</th><td>  A</td><td>B</td><td>C</td><td>D</td><td>E</td><td>F</td><td>G</td><td>H</td><td>I</td><td>J</td><td>K</td><td>L</td><td>M</td><td>N</td><td>O</td><td>P</td><td>Q</td><td>R</td><td>S</td><td>T</td><td>U</td><td>V</td><td>W</td><td>X</td><td>Y</td><td>Z</td></tr><tr style="vertical-align:top"><th scope="row">  Cipher</th><td> X</td><td>Y</td><td>Z</td><td>A</td><td>B</td><td>C</td><td>D</td><td>E</td><td>F</td><td>G</td><td>H</td><td>I</td><td>J</td><td>K</td><td>L</td><td>M</td><td>N</td><td>O</td><td>P</td><td>Q</td><td>R</td><td>S</td><td>T</td><td>U</td><td>V</td><td>W</td></tr></tbody></table>
    
Plaintext:  THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG<br>
Ciphertext: QEB NRFZH YOLTK CLU GRJMP LSBO QEB IXWV ALD<br><br>


Write two functions :<br>
    encrypt() convert a given text to caeser cipher<br>
    decrypt() decrypt the cipher back to text<br>

In [ ]:
#Answer
def encrypt(text,s):
    result = ""
 
    # traverse text
    for i in range(len(text)):
        char = text[i]
 
        # Encrypt uppercase characters
        if (char.isupper()):
            result += chr((ord(char) + s-65) % 26 + 65)
 
        # Encrypt lowercase characters
        else:
            result += chr((ord(char) + s - 97) % 26 + 97)

    return result

#check the above function
text =str(input("Enter text: "))
s = 23
print (f"Text  : {text}")
print (f"Shift : {str(s)}")
c=encrypt(text,s)
print (f"Cipher: {c}")

print (f"Decrypted: {encrypt(c,26-s)}")

Enter text:  THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG
Text  :  THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG
Shift : 23
Cipher: kQEBkNRFZHkYOLTKkCLUkGRJMPkLSBOkQEBkIXWVkALD
Decrypted: nTHEnQUICKnBROWNnFOXnJUMPSnOVERnTHEnLAZYnDOG


15. Counting the frequencies in a list and create a dictionary to store the count of all unique elements in the list

In [ ]:
#Answer
def CountFrequency(my_list):
 
    # Creating an empty dictionary
    freq = {}
    for item in my_list:
        if (item in freq):
            freq[item] += 1
        else:
            freq[item] = 1
 
    return freq

my_list =input("enter list: ").split()
 
CountFrequency(my_list)

enter list: 1 2 3 4 5 4 3 2 3 4 5


{'1': 1, '2': 2, '3': 3, '4': 3, '5': 2}

# String

In [ ]:
var1 = 'Hello World!'
var2 = "Python Programming"

print("var1[0]: ", var1[0])
print("var2[1:5]: ", var2[1:5])

16. Python program to check if a string is palindrome or not

In [ ]:
#Answer
s=str(input("enter string : "))
r=s[::-1]
if r==s:
  print("Its a palindrome")
else:
  print("Not a palindrome")

enter string : tenet
Its a palindrome


17. Remove all duplicates from a given string in Python

In [ ]:
#Answer

def removeDuplicate(stri):
    s=set(stri)
    s="".join(s)
    print("Without duplicates:",s)


stri=input("enter string: ")
removeDuplicate(stri)


enter string: muhammad ashiq ameer
Without duplicates: mhqsde arui


18. Program to count the number of words, characters and numbers in a paragraph

In [ ]:
#Answer
total_digits=0
test_string =input("Enter string: ")
res = len(test_string.split())
for s in test_string:
    # if character is digit (return True)
    if s.isnumeric():
        total_digits += 1

length=len(test_string)-test_string.count(" ") 

print(f"The number of words in string are : {res-total_digits}")
print(f"The number of letters in string are : {length}")
print(f"The no. of numbers in the string are : {total_digits}")

Enter string: muhammad ashiq ameer 1 2 3
The number of words in string are : 3
The number of letters in string are : 21
The no. of numbers in the string are : 3


19) Write a program to accept a list of strings and create a new list that consists of those strings
    with their first characters removed.
    
        Enter a list of strings: ["red", "green", "blue", "pink", "cyan"]
        List after removing first characters:['ed', 'reen', 'lue', 'ink', 'yan']

In [ ]:
#Answer
l1 = input("Enter a list of strings: ").split()
l2 = []

for i in range(len(l1)):
    l2.append(l1[i][1:])

print("List after removing first characters:")
print(l2)

Enter a list of strings: red green blue pink cyan
List after removing first characters:
['ed', 'reen', 'lue', 'ink', 'yan']


20) Write a program to print the length of the longest string in a list of user input strings.

        The original list : ['gfg', 'is', 'best', 'for', 'geeks']
        Maximum length string is : geeks

In [ ]:
#Answer
  
test_list=input("Enter list of strings : ").split()
res = max(test_list, key = len)

print("Maximum length string is : " + res)


Enter list of strings : gfg is best for geeks
Maximum length string is : geeks


# Matrix

In [ ]:
r = int(input())
c = int(input())
#  Complete
matrix = []
for i in range(r):
    row = input()
    row = [int(i) for i in row.split()]
    matrix.append(row)

print(matrix)

21) Write a function to accept a n x n matrix and find its transpose

In [ ]:
import numpy as np

M,N=input("Enter order of matrix: ").split()
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries).reshape(int(N), int(M))
print(matrix)
print(f"Transpose : ")
matrix.transpose()

Enter order of matrix: 3 3
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose : 


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

22) Write a program to read 2 matrices and find sum, difference and multiply.

In [ ]:
import numpy as np
N=input("Enter order of square matrix: ")
def createMatrix(n):
  matrix = []
  # taking RxC matrix from the user
  for i in range(int(n)):
    # empty row
    row = []
    for j in range(int(n)):
      # asking the user to input the number
      # converts the input to int as the default one is string
      element = int(input())
      # appending the element to the 'row'
      row.append(element)
    # appending the 'row' to the 'matrix'
    matrix.append(row)
  return matrix
print("Enter 1st matrix: \n")
A=createMatrix(N)
print("Enter 2nd matrix: \n")
B=createMatrix(N)
print(A)
print(B)
sum=np.add(A,B)
dif=np.subtract(A,B)
mul=np.dot(A,B)
print("sum:")
print(sum)
print("difference:")
print(dif)
print("product: ")
print(mul)

Enter order of square matrix: 3
Enter 1st matrix: 

1
2
3
4
5
6
7
8
9
Enter 2nd matrix: 

9
8
7
6
5
4
3
2
1
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]
sum:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
difference:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
product: 
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
